//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "retreat_reviews")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub review_id: i64,
    pub user_id: i64,
    pub retreat_id: i64,
    #[sea_orm(column_type = "Double")]
    pub rating: f64,
    #[sea_orm(column_type = "Text", nullable)]
    pub review: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::retreats::Entity",
        from = "Column::RetreatId",
        to = "super::retreats::Column::RetreatId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Retreats,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::retreats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Retreats.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
