//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "retreat_galleries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub gallery_id: i64,
    pub retreat_id: i64,
    #[sea_orm(column_type = "Text")]
    pub image_path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub caption: Option<String>,
    pub order: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: Option<i64>,
    pub updated_by: Option<i64>,
    pub gallery_category_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::gallery_categories::Entity",
        from = "Column::GalleryCategoryId",
        to = "super::gallery_categories::Column::GalleryCategoryId",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    GalleryCategories,
    #[sea_orm(
        belongs_to = "super::retreats::Entity",
        from = "Column::RetreatId",
        to = "super::retreats::Column::RetreatId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Retreats,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::UserId",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedBy",
        to = "super::users::Column::UserId",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Users1,
}

impl Related<super::gallery_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GalleryCategories.def()
    }
}

impl Related<super::retreats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Retreats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
