//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "retreats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub retreat_id: i64,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub category_id: i64,
    #[sea_orm(unique)]
    pub slug: String,
    pub social_links: Json,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub logo: Option<String>,
    pub latitude: Option<Decimal>,
    pub longitude: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub address: Option<String>,
    pub budget_min: Option<Decimal>,
    pub budget_max: Option<Decimal>,
    pub is_published: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: Option<i64>,
    pub updated_by: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::CategoryId",
        to = "super::categories::Column::CategoryId",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Categories,
    #[sea_orm(has_many = "super::retreat_users::Entity")]
    RetreatUsers,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedBy",
        to = "super::users::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users1,
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::retreat_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RetreatUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
